// GENERATED by docs/proposals/ironsights_2026-09-28/engine/gen_sights_header.py from sights.json - do not edit.
// HZM coop [ironsights 2026-09-28] per-weapon iron-sight geometry for the ADS sight solve.
#pragma once

typedef struct {
    const char *tiki;   // weapon TIKI path (cgi.TIKI_Name of the attached gun)
    const char *name;   // weapon name (configstring) - NULL when that name is shared by another mesh
    float       F[3];   // aim feature (post tip / hood centre), weapon model space
    float       R[3];   // rear feature (aperture centre / notch shoulders / leaf top)
    float       delta;  // R sits this far below F in the aligned picture (radians)
    float       U[3];   // the gun UP direction (sight side) in model space - for the cant solve
    float       relief; // eye relief: eye -> rear sight along the view (units); 0 = keep the animation value
} adsSight_t;

static const adsSight_t s_adsSights[] = {
    {"models/weapons/arisaka.tik", "Arisaka Type 99", {44.0557f, -0.9035f, -4.6376f}, {3.5564f, -0.9035f, -4.3424f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // arisaka_type_99
    {"models/weapons/bar.tik", "BAR", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_bar1918.tik", "Lewis Gun", {35.6064f, -1.2984f, -5.4866f}, {-0.7600f, -1.2984f, -5.1210f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar_wwi
    {"models/weapons/bar_bar1918a.tik", "BAR (M1918 Classic)", {39.5157f, -0.7207f, -4.5786f}, {-1.8449f, -0.7590f, -4.2070f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar_m1918a
    {"models/weapons/bar_bar1918a1.tik", "BAR (M1918A1)", {39.5157f, -0.7207f, -4.5786f}, {-1.8449f, -0.7590f, -4.2070f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar_m1918a
    {"models/weapons/bar_bar1918a2.tik", "BAR (M1918A2)", {39.5157f, -0.7207f, -4.5786f}, {-1.8449f, -0.7590f, -4.2070f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar_m1918a
    {"models/weapons/bar_bloody.tik", "BAR (Bloody)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_blued.tik", "BAR (Blued)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_camo_desert.tik", "BAR (Desert)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_camo_winter.tik", "BAR (Winter)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_camo_woodland.tik", "BAR (Woodland)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_chrome.tik", "BAR (Chrome)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_gold.tik", "BAR (Gold)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar
    {"models/weapons/bar_pabar.tik", "BAR (Pacific)", {35.6267f, -0.7789f, -4.2493f}, {-0.3181f, -0.7833f, -4.3841f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bar_pacific
    {"models/weapons/bazooka.tik", "Bazooka", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_bloody.tik", "Bazooka (Bloody)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_blued.tik", "Bazooka (Blued)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_camo_desert.tik", "Bazooka (Desert)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_camo_winter.tik", "Bazooka (Winter)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_camo_woodland.tik", "Bazooka (Woodland)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_chrome.tik", "Bazooka (Chrome)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_gold.tik", "Bazooka (Gold)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/bazooka_guanbazooka.tik", "Bazooka (Realistic)", {24.0418f, -1.7442f, -6.2576f}, {-15.9600f, -1.7440f, -6.2575f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // bazooka
    {"models/weapons/berettasilenced.tik", "Silenced Beretta", {22.6420f, -0.3000f, -4.1660f}, {0.2000f, -0.2440f, -3.9000f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_beretta
    {"models/weapons/carbine.tik", "M1 Carbine", {32.3431f, -0.6477f, -5.2364f}, {2.5817f, -0.9278f, -5.2889f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carbine
    {"models/weapons/colt45.tik", "Colt 45", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_bloody.tik", "Colt 45 (Bloody)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_bloodyeic.tik", "Colt 45 (M1911 Bloody EiC)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_blued.tik", "Colt 45 (Blued)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_camo_desert.tik", "Colt 45 (Desert)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_camo_winter.tik", "Colt 45 (Winter)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_camo_woodland.tik", "Colt 45 (Woodland)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_chrome.tik", "Colt 45 (Chrome)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_colt1911w.tik", "Webley Mk VI", {12.3699f, -0.7518f, -5.1841f}, {1.9802f, -0.7098f, -4.9767f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45_m1911_wwi
    {"models/weapons/colt45_coltpa.tik", "Colt 45 (Pacific)", {10.8861f, -0.6965f, -3.3219f}, {0.7817f, -0.6896f, -3.4430f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45_pacific
    {"models/weapons/colt45_covert.tik", "Colt 45 (M1911 Covert)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_drbond.tik", "Colt 45 (1911 Classic)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_gold.tik", "Colt 45 (Gold)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_guancolt.tik", "Colt 45 (Guanshire)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt45_lv_ttcolt.tik", "Colt 45 (Team Tactics)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/colt_silenced.tik", "Silenced Colt .45", {21.4745f, -0.5994f, -3.3279f}, {0.7817f, -0.6896f, -3.4430f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_colt_45
    {"models/weapons/dbno_pistol.tik", "Colt 45", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_bloody.tik", "Colt 45 (Bloody)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_blued.tik", "Colt 45 (Blued)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_camo_desert.tik", "Colt 45 (Desert)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_camo_winter.tik", "Colt 45 (Winter)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_camo_woodland.tik", "Colt 45 (Woodland)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_chrome.tik", "Colt 45 (Chrome)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/dbno_pistol_gold.tik", "Colt 45 (Gold)", {10.4327f, -0.7252f, -3.4478f}, {0.5056f, -0.7574f, -3.1925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // colt_45
    {"models/weapons/delisle.tik", "DeLisle", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_bloody.tik", "DeLisle (Bloody)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_blued.tik", "DeLisle (Blued)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_camo_desert.tik", "DeLisle (Desert)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_camo_winter.tik", "DeLisle (Winter)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_camo_woodland.tik", "DeLisle (Woodland)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_chrome.tik", "DeLisle (Chrome)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_gold.tik", "DeLisle (Gold)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_lv_ttdelisle.tik", "DeLisle (Team Tactics)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/delisle_lv_wdelisle.tik", "DeLisle (Wehrmacht)", {29.4883f, -1.2419f, -5.4481f}, {12.5715f, -1.2419f, -5.5163f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // delisle
    {"models/weapons/dp28.tik", "DP-28", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_bloody.tik", "DP-28 (Bloody)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_blued.tik", "DP-28 (Blued)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_camo_desert.tik", "DP-28 (Desert)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_camo_winter.tik", "DP-28 (Winter)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_camo_woodland.tik", "DP-28 (Woodland)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_chrome.tik", "DP-28 (Chrome)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/dp28_gold.tik", "DP-28 (Gold)", {27.1920f, -0.2823f, -5.4864f}, {1.5534f, -0.2849f, -5.1359f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // dp_28
    {"models/weapons/enfield.tik", "Lee-Enfield", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_bloody.tik", "Lee-Enfield (Bloody)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_blued.tik", "Lee-Enfield (Blued)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_camo_desert.tik", "Lee-Enfield (Desert)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_camo_winter.tik", "Lee-Enfield (Winter)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_camo_woodland.tik", "Lee-Enfield (Woodland)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_chrome.tik", "Lee-Enfield (Chrome)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_gold.tik", "Lee-Enfield (Gold)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_hobbsenfurb.tik", "Lee-Enfield (Urban Camo)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite.tik", "Lee-Enfield", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_bloody.tik", "Lee-Enfield (Bloody)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_blued.tik", "Lee-Enfield (Blued)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_camo_desert.tik", "Lee-Enfield (Desert)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_camo_winter.tik", "Lee-Enfield (Winter)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_camo_woodland.tik", "Lee-Enfield (Woodland)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_chrome.tik", "Lee-Enfield (Chrome)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lite_gold.tik", "Lee-Enfield (Gold)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_lv_ttenfield.tik", "Lee-Enfield (Team Tactics)", {39.9964f, -1.0580f, -4.6575f}, {1.8809f, -1.0166f, -5.2061f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield
    {"models/weapons/enfield_p14.tik", "Lee-Enfield (P14 Enfield)", {44.8347f, -1.2130f, -4.6087f}, {1.7200f, -1.0576f, -5.8228f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // lee_enfield_p14_enfield
    {"models/weapons/garand_silenced.tik", "Silenced M1 Garand", {35.7403f, -0.4476f, -5.5440f}, {2.7682f, -0.8965f, -5.3283f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_m1_garand
    {"models/weapons/greasegun.tik", "M3 Grease Gun", {17.3714f, -1.0390f, -6.3154f}, {-0.9848f, -1.2664f, -6.2047f}, 0.000000f, {0.012f, -0.000f, -1.000f}, 0.000f}, // m3_grease_gun
    {"models/weapons/greasegun_silenced.tik", "Silenced Grease Gun", {17.3714f, -1.0390f, -6.3154f}, {-0.9848f, -1.2664f, -6.2047f}, 0.000000f, {0.012f, -0.000f, -1.000f}, 0.000f}, // silenced_grease_gun
    {"models/weapons/it_w_beretta.tik", "Beretta", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_bloody.tik", "Beretta (Bloody)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_blued.tik", "Beretta (Blued)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_camo_desert.tik", "Beretta (Desert)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_camo_winter.tik", "Beretta (Winter)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_camo_woodland.tik", "Beretta (Woodland)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_chrome.tik", "Beretta (Chrome)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_gold.tik", "Beretta (Gold)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_beretta_lv_ttberetta.tik", "Beretta (Team Tactics)", {8.0632f, 0.0008f, -4.0094f}, {-1.2912f, -0.1642f, -3.7957f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta
    {"models/weapons/it_w_breda.tik", "Breda", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_bloody.tik", "Breda (Bloody)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_blued.tik", "Breda (Blued)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_camo_desert.tik", "Breda (Desert)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_camo_winter.tik", "Breda (Winter)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_camo_woodland.tik", "Breda (Woodland)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_chrome.tik", "Breda (Chrome)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_breda_gold.tik", "Breda (Gold)", {30.0767f, -0.0170f, -4.4031f}, {-1.3000f, -0.0180f, -4.4600f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // breda
    {"models/weapons/it_w_carcano.tik", "Carcano", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_bloody.tik", "Carcano (Bloody)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_blued.tik", "Carcano (Blued)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_camo_desert.tik", "Carcano (Desert)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_camo_winter.tik", "Carcano (Winter)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_camo_woodland.tik", "Carcano (Woodland)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_chrome.tik", "Carcano (Chrome)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_gold.tik", "Carcano (Gold)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite.tik", "Carcano", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_bloody.tik", "Carcano (Bloody)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_blued.tik", "Carcano (Blued)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_camo_desert.tik", "Carcano (Desert)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_camo_winter.tik", "Carcano (Winter)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_camo_woodland.tik", "Carcano (Woodland)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_chrome.tik", "Carcano (Chrome)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lite_gold.tik", "Carcano (Gold)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_carcano_lv_ttcarcano.tik", "Carcano (Team Tactics)", {36.2992f, -1.3843f, -4.6756f}, {12.2440f, -1.3835f, -4.9170f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // carcano
    {"models/weapons/it_w_moschetto.tik", "Moschetto", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_bloody.tik", "Moschetto (Bloody)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_blued.tik", "Moschetto (Blued)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_camo_desert.tik", "Moschetto (Desert)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_camo_winter.tik", "Moschetto (Winter)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_camo_woodland.tik", "Moschetto (Woodland)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_chrome.tik", "Moschetto (Chrome)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/it_w_moschetto_gold.tik", "Moschetto (Gold)", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // moschetto
    {"models/weapons/johnson_m1941.tik", "Johnson M1941", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_bloody.tik", "Johnson M1941 (Bloody)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_blued.tik", "Johnson M1941 (Blued)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_camo_desert.tik", "Johnson M1941 (Desert)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_camo_winter.tik", "Johnson M1941 (Winter)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_camo_woodland.tik", "Johnson M1941 (Woodland)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_chrome.tik", "Johnson M1941 (Chrome)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/johnson_m1941_gold.tik", "Johnson M1941 (Gold)", {42.1745f, -0.9927f, -5.4646f}, {2.6826f, -0.9010f, -5.2696f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // johnson_m1941
    {"models/weapons/kar98.tik", "Mauser KAR 98K", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_bloody.tik", "Mauser KAR 98K (Bloody)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_blued.tik", "Mauser KAR 98K (Blued)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_camo_desert.tik", "Mauser KAR 98K (Desert)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_camo_winter.tik", "Mauser KAR 98K (Winter)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_camo_woodland.tik", "Mauser KAR 98K (Woodland)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_chrome.tik", "Mauser KAR 98K (Chrome)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_g98.tik", "Mauser KAR 98K (Gewehr 98)", {53.4789f, -0.5328f, -4.9143f}, {15.7934f, -0.6659f, -5.4564f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98_g98
    {"models/weapons/kar98_gold.tik", "Mauser KAR 98K (Gold)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_hobbskarwood.tik", "Mauser KAR 98K (Woodland Camo)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_hobbskarworn.tik", "Mauser KAR 98K (Worn)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite.tik", "Mauser KAR 98K", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_bloody.tik", "Mauser KAR 98K (Bloody)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_blued.tik", "Mauser KAR 98K (Blued)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_camo_desert.tik", "Mauser KAR 98K (Desert)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_camo_winter.tik", "Mauser KAR 98K (Winter)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_camo_woodland.tik", "Mauser KAR 98K (Woodland)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_chrome.tik", "Mauser KAR 98K (Chrome)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lite_gold.tik", "Mauser KAR 98K (Gold)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/kar98_lv_ttkar98.tik", "Mauser KAR 98K (Team Tactics)", {43.8243f, -0.7636f, -5.4884f}, {12.0450f, -0.7829f, -4.8144f}, 0.014000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // kar98
    {"models/weapons/lugerp08.tik", "Luger P08", {12.3196f, -0.4455f, -3.3342f}, {-1.0978f, -0.5160f, -3.1790f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // luger_p08
    {"models/weapons/lugerp08silenced.tik", "Silenced Luger P08", {12.3196f, -0.4455f, -3.3342f}, {-1.0978f, -0.5160f, -3.1790f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_luger_p08
    {"models/weapons/m10_revolver.tik", "S&W M10 .38", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_bloody.tik", "S&W M10 .38 (Bloody)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_blued.tik", "S&W M10 .38 (Blued)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_camo_desert.tik", "S&W M10 .38 (Desert)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_camo_winter.tik", "S&W M10 .38 (Winter)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_camo_woodland.tik", "S&W M10 .38 (Woodland)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_chrome.tik", "S&W M10 .38 (Chrome)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m10_revolver_gold.tik", "S&W M10 .38 (Gold)", {10.7147f, -0.9724f, -4.3070f}, {3.0000f, -0.8500f, -4.1528f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // s_w_m10_38
    {"models/weapons/m1_garand.tik", "M1 Garand", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_bloody.tik", "M1 Garand (Bloody)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_blued.tik", "M1 Garand (Blued)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_camo_desert.tik", "M1 Garand (Desert)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_camo_winter.tik", "M1 Garand (Winter)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_camo_woodland.tik", "M1 Garand (Woodland)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_chrome.tik", "M1 Garand (Chrome)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_gold.tik", "M1 Garand (Gold)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_guangarand.tik", "M1 Garand (Guanshire)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite.tik", "M1 Garand", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_bloody.tik", "M1 Garand (Bloody)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_blued.tik", "M1 Garand (Blued)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_camo_desert.tik", "M1 Garand (Desert)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_camo_winter.tik", "M1 Garand (Winter)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_camo_woodland.tik", "M1 Garand (Woodland)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_chrome.tik", "M1 Garand (Chrome)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lite_gold.tik", "M1 Garand (Gold)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_lv_ttgarand.tik", "M1 Garand (Team Tactics)", {40.6610f, -0.4358f, -5.6579f}, {3.5880f, -0.8877f, -5.4777f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand
    {"models/weapons/m1_garand_pagarand.tik", "M1 Garand (Pacific)", {35.7871f, -0.9522f, -5.2110f}, {2.8589f, -0.9514f, -5.1679f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // garand_pacific
    {"models/weapons/mauser_c96.tik", "Mauser C96", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_bloody.tik", "Mauser C96 (Bloody)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_blued.tik", "Mauser C96 (Blued)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_c96trench.tik", "Mauser C96 (Trench C96)", {15.9643f, -0.5887f, -4.5297f}, {1.1567f, -0.6979f, -4.6554f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96_trench_c96
    {"models/weapons/mauser_c96_camo_desert.tik", "Mauser C96 (Desert)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_camo_winter.tik", "Mauser C96 (Winter)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_camo_woodland.tik", "Mauser C96 (Woodland)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_chrome.tik", "Mauser C96 (Chrome)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mauser_c96_gold.tik", "Mauser C96 (Gold)", {15.4048f, -0.8000f, -3.8262f}, {4.5035f, -0.8461f, -4.3355f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mauser_c96
    {"models/weapons/mg42portable.tik", "MG42", {36.5299f, -1.5014f, -6.2511f}, {14.0737f, -1.6420f, -6.6459f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mg42
    {"models/weapons/moschetto.tik", "Beretta M38", {29.9974f, 0.5765f, -4.6223f}, {7.2603f, -0.0116f, -4.7814f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // beretta_m38
    {"models/weapons/mosin_nagant_rifle.tik", "Mosin Nagant Rifle", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_bloody.tik", "Mosin Nagant Rifle (Bloody)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_blued.tik", "Mosin Nagant Rifle (Blued)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_camo_desert.tik", "Mosin Nagant Rifle (Desert)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_camo_winter.tik", "Mosin Nagant Rifle (Winter)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_camo_woodland.tik", "Mosin Nagant Rifle (Woodland)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_chrome.tik", "Mosin Nagant Rifle (Chrome)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_gold.tik", "Mosin Nagant Rifle (Gold)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_hobbsmosinur.tik", "Mosin Nagant Rifle (Urban Camo)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite.tik", "Mosin Nagant Rifle", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_bloody.tik", "Mosin Nagant Rifle (Bloody)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_blued.tik", "Mosin Nagant Rifle (Blued)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_camo_desert.tik", "Mosin Nagant Rifle (Desert)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_camo_winter.tik", "Mosin Nagant Rifle (Winter)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_camo_woodland.tik", "Mosin Nagant Rifle (Woodland)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_chrome.tik", "Mosin Nagant Rifle (Chrome)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lite_gold.tik", "Mosin Nagant Rifle (Gold)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mosin_nagant_rifle_lv_ttmosin.tik", "Mosin Nagant Rifle (Team Tactics)", {45.5440f, -0.8946f, -4.5793f}, {14.6681f, -1.0825f, -4.8724f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mosin_nagant_rifle
    {"models/weapons/mp40.tik", "MP40", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_bloody.tik", "MP40 (Bloody)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_blued.tik", "MP40 (Blued)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_camo_desert.tik", "MP40 (Desert)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_camo_winter.tik", "MP40 (Winter)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_camo_woodland.tik", "MP40 (Woodland)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_chrome.tik", "MP40 (Chrome)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_gold.tik", "MP40 (Gold)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_guanmp40.tik", "MP40 (Guanshire)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_guanmp40s.tik", "MP40 (Silver)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_lv_mp75.tik", "MP40 (MP 75 Ausf D)", {28.4260f, -0.8863f, -5.8894f}, {6.9961f, -0.8850f, -5.8909f}, 0.016000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40
    {"models/weapons/mp40_mp18.tik", "MP40 (MP18)", {25.7280f, -2.2582f, -4.6120f}, {1.9786f, -2.3928f, -5.6721f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // mp40_mp18
    {"models/weapons/mp40_mp40r2.tik", "MP40 (Reactivated)", {28.1970f, -0.9201f, -6.0070f}, {6.9434f, -1.1789f, -6.0653f}, 0.000000f, {0.012f, -0.000f, -1.000f}, 0.000f}, // mp40_reactivated
    {"models/weapons/mp40silenced.tik", "Silenced MP40", {28.2630f, -1.0820f, -5.5754f}, {6.7486f, -0.9251f, -5.8910f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_mp40
    {"models/weapons/mp44.tik", "StG 44", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_bloody.tik", "StG 44 (Bloody)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_blued.tik", "StG 44 (Blued)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_camo_desert.tik", "StG 44 (Desert)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_camo_winter.tik", "StG 44 (Winter)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_camo_woodland.tik", "StG 44 (Woodland)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_chrome.tik", "StG 44 (Chrome)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_dhstg44ss.tik", "StG 44 (SS Edition)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_gold.tik", "StG 44 (Gold)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_guanmp44.tik", "StG 44 (Guanshire)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_lv_ttmp44.tik", "StG 44 (Team Tactics)", {28.9093f, -0.8875f, -7.0093f}, {6.5820f, -0.8896f, -7.5520f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44
    {"models/weapons/mp44_mp44strap.tik", "StG 44 (Strapped)", {28.8579f, -0.8523f, -6.7881f}, {6.5802f, -0.9143f, -7.1918f}, 0.022000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // stg44_strap
    {"models/weapons/nagant_revolver.tik", "Nagant Revolver", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_bloody.tik", "Nagant Revolver (Bloody)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_blued.tik", "Nagant Revolver (Blued)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_camo_desert.tik", "Nagant Revolver (Desert)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_camo_winter.tik", "Nagant Revolver (Winter)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_camo_woodland.tik", "Nagant Revolver (Woodland)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_chrome.tik", "Nagant Revolver (Chrome)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nagant_revolver_gold.tik", "Nagant Revolver (Gold)", {11.4552f, -0.7404f, -3.8464f}, {2.4010f, -0.7014f, -3.5230f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nagant_revolver
    {"models/weapons/nambu.tik", "Nambu Type 14", {10.4347f, -0.6205f, -3.6020f}, {-1.3752f, -0.6205f, -3.6038f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // nambu_type_14
    {"models/weapons/p38 - copy.tik", "Walther P38", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38.tik", "Walther P38", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_bloody.tik", "Walther P38 (Bloody)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_blued.tik", "Walther P38 (Blued)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_camo_desert.tik", "Walther P38 (Desert)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_camo_winter.tik", "Walther P38 (Winter)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_camo_woodland.tik", "Walther P38 (Woodland)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_chrome.tik", "Walther P38 (Chrome)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_gold.tik", "Walther P38 (Gold)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_guanp38.tik", "Walther P38 (Guanshire)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38_lv_ttp38.tik", "Walther P38 (Team Tactics)", {10.4137f, -0.7010f, -3.2568f}, {0.3414f, -0.7074f, -3.1553f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_p38
    {"models/weapons/p38silenced.tik", "Silenced Walther P38", {10.3777f, -0.6320f, -3.3742f}, {0.4237f, -0.5470f, -3.2825f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_walther_p38
    {"models/weapons/panzerschreck.tik", "Panzerschreck", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_bloody.tik", "Panzerschreck (Bloody)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_blued.tik", "Panzerschreck (Blued)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_camo_desert.tik", "Panzerschreck (Desert)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_camo_winter.tik", "Panzerschreck (Winter)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_camo_woodland.tik", "Panzerschreck (Woodland)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_chrome.tik", "Panzerschreck (Chrome)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_gold.tik", "Panzerschreck (Gold)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/panzerschreck_lv_ofenrohr.tik", "Panzerschreck (Ofenrohr)", {25.5321f, -2.5166f, -8.4989f}, {-14.4700f, -2.5165f, -8.4990f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // panzerschreck
    {"models/weapons/ppk.tik", "Walther PPK", {16.2018f, -0.7610f, -2.7442f}, {0.9415f, -0.7234f, -2.6925f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // walther_ppk
    {"models/weapons/ppsh43silenced.tik", "Silenced PPS-43", {28.1032f, -0.1726f, -6.9711f}, {7.7039f, -0.4670f, -6.1481f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_pps_43
    {"models/weapons/ppsh_smg.tik", "PPSH SMG", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_bloody.tik", "PPSH SMG (Bloody)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_blued.tik", "PPSH SMG (Blued)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_camo_desert.tik", "PPSH SMG (Desert)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_camo_winter.tik", "PPSH SMG (Winter)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_camo_woodland.tik", "PPSH SMG (Woodland)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_chrome.tik", "PPSH SMG (Chrome)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/ppsh_smg_gold.tik", "PPSH SMG (Gold)", {20.3483f, 0.2231f, -5.8540f}, {2.7031f, 0.2195f, -5.5750f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // ppsh_smg
    {"models/weapons/shotgun.tik", "Shotgun", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_authwinch.tik", "Shotgun (Authentic Wood)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_bloody.tik", "Shotgun (Bloody)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_blued.tik", "Shotgun (Blued)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_camo_desert.tik", "Shotgun (Desert)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_camo_winter.tik", "Shotgun (Winter)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_camo_woodland.tik", "Shotgun (Woodland)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_chrome.tik", "Shotgun (Chrome)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_dhshotblack.tik", "Shotgun (Black Tactical)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_dhshotchrome.tik", "Shotgun (Chrome Tactical)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_gold.tik", "Shotgun (Gold)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_guanshotty.tik", "Shotgun (Guanshire)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_hobbsshotty.tik", "Shotgun (Recoil)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/shotgun_lv_ttshotgun.tik", "Shotgun (Team Tactics)", {30.7989f, -1.3824f, -4.7204f}, {6.5813f, -1.4207f, -4.0041f}, 0.004000f, {-0.043f, -0.139f, -0.989f}, 0.000f}, // shotgun
    {"models/weapons/silencedpistol.tik", "Hi-Standard Silenced", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_bloody.tik", "Hi-Standard Silenced (Bloody)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_blued.tik", "Hi-Standard Silenced (Blued)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_camo_desert.tik", "Hi-Standard Silenced (Desert)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_camo_winter.tik", "Hi-Standard Silenced (Winter)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_camo_woodland.tik", "Hi-Standard Silenced (Woodland)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_chrome.tik", "Hi-Standard Silenced (Chrome)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/silencedpistol_gold.tik", "Hi-Standard Silenced (Gold)", {23.1712f, -0.4575f, -3.2698f}, {0.5516f, -0.4621f, -3.3157f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // hi_standard_silenced
    {"models/weapons/springfield_unscoped.tik", "Springfield M1903", {42.5482f, -0.7081f, -5.4116f}, {13.6566f, -0.9664f, -5.0911f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // springfield_unscoped
    {"models/weapons/sten.tik", "Sten Mark II", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_bloody.tik", "Sten Mark II (Bloody)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_blued.tik", "Sten Mark II (Blued)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_camo_desert.tik", "Sten Mark II (Desert)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_camo_winter.tik", "Sten Mark II (Winter)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_camo_woodland.tik", "Sten Mark II (Woodland)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_chrome.tik", "Sten Mark II (Chrome)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/sten_gold.tik", "Sten Mark II (Gold)", {21.7245f, -0.6818f, -4.7990f}, {-2.0997f, -0.6892f, -5.6021f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // sten_mark_ii
    {"models/weapons/svt_rifle.tik", "SVT 40", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_bloody.tik", "SVT 40 (Bloody)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_blued.tik", "SVT 40 (Blued)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_camo_desert.tik", "SVT 40 (Desert)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_camo_winter.tik", "SVT 40 (Winter)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_camo_woodland.tik", "SVT 40 (Woodland)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_chrome.tik", "SVT 40 (Chrome)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_gold.tik", "SVT 40 (Gold)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/svt_rifle_hobbssvtwood.tik", "SVT 40 (Woodland Camo)", {46.6200f, -0.1311f, -4.4160f}, {15.3284f, -0.0697f, -5.4181f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // svt_40
    {"models/weapons/thompson50.tik", "Thompson 50rd", {23.0038f, -0.7292f, -5.3662f}, {-7.8194f, -0.7285f, -6.3634f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson_50rd
    {"models/weapons/thompsonsmg.tik", "Thompson", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_bloody.tik", "Thompson (Bloody)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_blued.tik", "Thompson (Blued)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_camo_desert.tik", "Thompson (Desert)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_camo_winter.tik", "Thompson (Winter)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_camo_woodland.tik", "Thompson (Woodland)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_chrome.tik", "Thompson (Chrome)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_gold.tik", "Thompson (Gold)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_guantommy.tik", "Thompson (Guanshire)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_hobbstomworn.tik", "Thompson (Worn)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_lv_famastommy.tik", "Thompson (FAMAS II)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_lv_tttommy.tik", "Thompson (Team Tactics)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson
    {"models/weapons/thompsonsmg_m1a1dk.tik", "Thompson (M1A1 Remodel)", {21.8651f, -0.7900f, -5.1164f}, {-6.3288f, -0.8099f, -5.1702f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson_m1a1
    {"models/weapons/thompsonsmg_tommy1928d.tik", "Thompson (1928 Tommy)", {23.6157f, -0.7918f, -5.6185f}, {-6.9362f, -0.7778f, -5.4238f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson_1928
    {"models/weapons/thompsonsmg_tommy27a1.tik", "Thompson (27A1 Commando)", {22.4168f, -0.8148f, -5.1548f}, {-6.7622f, -0.7969f, -5.5601f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson_27a1
    {"models/weapons/thompsonsmg_tommy28.tik", "Thompson (M1928)", {22.6248f, -0.7292f, -5.5323f}, {-6.3361f, -0.7285f, -5.8120f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // thompson_m1928
    {"models/weapons/tt33.tik", "TT-33 Tokarev", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_bloody.tik", "TT-33 Tokarev (Bloody)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_blued.tik", "TT-33 Tokarev (Blued)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_camo_desert.tik", "TT-33 Tokarev (Desert)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_camo_winter.tik", "TT-33 Tokarev (Winter)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_camo_woodland.tik", "TT-33 Tokarev (Woodland)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_chrome.tik", "TT-33 Tokarev (Chrome)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33_gold.tik", "TT-33 Tokarev (Gold)", {10.8151f, -0.6104f, -3.3761f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // tt_33_tokarev
    {"models/weapons/tt33silenced.tik", "Silenced TT-33", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_bloody.tik", "Silenced TT-33 (Bloody)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_blued.tik", "Silenced TT-33 (Blued)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_camo_desert.tik", "Silenced TT-33 (Desert)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_camo_winter.tik", "Silenced TT-33 (Winter)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_camo_woodland.tik", "Silenced TT-33 (Woodland)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_chrome.tik", "Silenced TT-33 (Chrome)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/tt33silenced_gold.tik", "Silenced TT-33 (Gold)", {19.8777f, -0.6620f, -3.7022f}, {0.3725f, -0.5703f, -3.3384f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // silenced_tt_33
    {"models/weapons/type100smg.tik", "Type 100 SMG", {22.4771f, -0.3800f, -3.4977f}, {-0.9447f, -1.3123f, -7.1554f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // type_100_smg
    {"models/weapons/uk_w_piat.tik", "PIAT", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_bloody.tik", "PIAT (Bloody)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_blued.tik", "PIAT (Blued)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_camo_desert.tik", "PIAT (Desert)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_camo_winter.tik", "PIAT (Winter)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_camo_woodland.tik", "PIAT (Woodland)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_chrome.tik", "PIAT (Chrome)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_piat_gold.tik", "PIAT (Gold)", {6.1039f, -2.0896f, -7.2842f}, {-9.2023f, -2.2167f, -7.4166f}, 0.003000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // piat
    {"models/weapons/uk_w_vickers.tik", "Vickers-Berthier", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_bloody.tik", "Vickers-Berthier (Bloody)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_blued.tik", "Vickers-Berthier (Blued)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_camo_desert.tik", "Vickers-Berthier (Desert)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_camo_winter.tik", "Vickers-Berthier (Winter)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_camo_woodland.tik", "Vickers-Berthier (Woodland)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_chrome.tik", "Vickers-Berthier (Chrome)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/uk_w_vickers_gold.tik", "Vickers-Berthier (Gold)", {40.1472f, 0.0050f, -5.8223f}, {3.0000f, -1.6000f, -5.8225f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // vickers_berthier
    {"models/weapons/webley_revolver.tik", "Webley Revolver", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_bloody.tik", "Webley Revolver (Bloody)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_blued.tik", "Webley Revolver (Blued)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_camo_desert.tik", "Webley Revolver (Desert)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_camo_winter.tik", "Webley Revolver (Winter)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_camo_woodland.tik", "Webley Revolver (Woodland)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_chrome.tik", "Webley Revolver (Chrome)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_gold.tik", "Webley Revolver (Gold)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/webley_revolver_lv_ttwebley.tik", "Webley Revolver (Team Tactics)", {14.8364f, -0.7711f, -4.7374f}, {4.3864f, -0.7711f, -4.4848f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // webley_revolver
    {"models/weapons/welrod.tik", "Welrod", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_bloody.tik", "Welrod (Bloody)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_blued.tik", "Welrod (Blued)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_camo_desert.tik", "Welrod (Desert)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_camo_winter.tik", "Welrod (Winter)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_camo_woodland.tik", "Welrod (Woodland)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_chrome.tik", "Welrod (Chrome)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
    {"models/weapons/welrod_gold.tik", "Welrod (Gold)", {8.4192f, -0.5264f, -3.5844f}, {-2.8424f, -0.6541f, -3.3819f}, 0.000000f, {0.000f, 0.000f, -1.000f}, 0.000f}, // welrod
};
